FORMAT: 1A

# Demo API

## Hello API

# Send Hello [/hello/{id}]

## 挨拶送信API [POST]

+ Parameters
    + id: 3 (number, required) - 挨拶送信先ID

+ Response 200 (application/json)
    + Body

        {
            "request": "ok",
            "message": "hello, Tom!"
        }